"""Stable identifiers for the Aderin demo. Kept deterministic for reproducibility."""

USER_AMARA = "user-amara"
USER_CHIDI = "user-chidi"
USER_FATIMA = "user-fatima"
USER_EMEKA = "user-emeka"
USER_NGOZI = "user-ngozi"
USER_ANON = "user-anon"
USER_IBRAHIM = "user-ibrahim"
USER_AMINA = "user-amina"

ROUTE_SHOP_HOME = "shop-home"
ROUTE_SHOP_HOME_ALT = "shop-home-alt"
ROUTE_STATION = "station-road"
ROUTE_CENTRAL = "central-avenue"
ROUTE_HILL = "hill-road"

REPORT_MARKET_1 = "report-market-01"
REPORT_MARKET_2 = "report-market-02"
REPORT_STATION_1 = "report-station-01"
REPORT_STATION_2 = "report-station-02"
REPORT_STATION_3 = "report-station-03"
REPORT_RIVER_CLEAR = "report-river-clear"
REPORT_CENTRAL_CLEAR = "report-central-clear"
REPORT_CENTRAL_CLEAR_2 = "report-central-clear-02"
